name: NPM Publish
description: Publish the package to NPM
inputs:
  token:
    required: true
    description: NPM token
  dry-run:
    required: false
    description: Dry run the publish
    default: false
  provenance:
    required: false
    description: Provenance
    default: false

branding:
  icon: package
  color: blue

runs:
  using: composite

  steps:
    # - name: Setup PNPM
    #   uses: pnpm/action-setup@v4

    # - name: Setup Node.js ${{ inputs.node-version }}
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: ${{ inputs.node-version }}
    #     cache: 'pnpm'

    # https://github.com/JS-DevTools/npm-publish
    - name: Publish to NPM
      id: publish
      uses: JS-DevTools/npm-publish@v3
      with:
        token: ${{ inputs.token }}
        dry-run: ${{ inputs.dry-run }}
        provenance: ${{ inputs.provenance }}

    - name: Post publish
      if: steps.publish.outputs.type != ''
      run: |
        echo "Published ${{ steps.publish.outputs.type }} version: ${{ steps.publish.outputs.version }}"

    - name: Publish skipped
      if: steps.publish.outputs.type == ''
      run: |
        echo "Version in package.json has not changed. Skipping."
        exit 0

    # https://github.com/ncipollo/release-action
    - name: Create Release
      if: steps.publish.outputs.type != ''
      id: release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        generateReleaseNotes: true
        commit: ${{ github.sha }}
        draft: true
        name: v${{ steps.publish.outputs.version }}
        tag: v${{ steps.publish.outputs.version }}